### ISSUE TITLE
"ESP8266 server connection error, checking wifi" (high port number)

### ISSUE THREAD

**Issue by harrio** [McOffsky/Arduino_ESP8266_HTTP_Client#1]
I succesfully tried the example script against arduino.cc/asciilogo.txt . So my module definitely works ok and is capable of making requests and reading responses. 

Then I modified the script to make a GET request to my own http-kit server which just returns one character in the response with content-type text/plain. (I've tested the server with httpie and the response is ok.) For some reason the program starts printing "ESP8266 server connection error, checking wifi" forever in a very quick loop. Any idea why this happens?

**Comment by harrio** [comment]
The problem seems to be with the port number. If I use 80, everything works. If 3000, the error occurs. For some reason port 3000 ends up as 184 when it's passed to the wifi module.

**Comment by McOffsky** [comment]
Port number is stored as uint8_t for lower memory usage, so you cannot connect on ports higher than 255. To change this for int with bigger range you need to edit line 141 and 187 of esp8266.h file and 96 line of esp8266.cpp, those are all declaracions of port variable.

**Comment by harrio** [comment]
Thanks, works perfectly now.
